name: Convox Multitool
description: Convox CLI interface
author: Beast Awakens
icon: cloud
color: blue
inputs:
  action:
    description: Convox command to action
    required: true
    type: choice
    options:
      - build
      - build-migrate
      - create
      - deploy
      - destroy
      - env-set
      - find-release
      - get-scale
      - login
      - login-user
      - promote
      - rack-param
      - run
      - scale
  password:
    description: Convox deploy key value
  host:
    description: Convox Console host address
    required: false
    default: console.convox.com
  token:
    description: Convox Console token value
  rack:
    description: Convox Rack name
  app:
    description: Convox app name
  destination-app:
    description: Convox destination app name for build migration
  destination-rack:
    description: Convox destination rack name for build migration
  description:
    description: Convox build description
  cached:
    description: Whether to utilise the docker cache during the build
    required: false
    default: true
  manifest:
    description: Use a custom path for your convox.yml
    required: false
  param-name:
    description: Name of the parameter to set
  param-value:
    description: Value of the parameter to set
  release:
    description: ID of the release to promote. Only needed if you have not run a build step first or you wish to override the release id from the build
    required: false
  service:
    description: The service to run the command against
  command:
    description: The command to be run
  count:
    description: The number of instances to scale to
outputs:
  release:
    description: Release ID of the created build
  desired:
    description: Count of desired instances
  running:
    description: Count of running instances
  cpu:
    description: CPU scale value
  memory:
    description: Memory scale value
  scaling_event:
    description: Boolean value to indicate if a scaling event is in progress
  env:
    description: Environment variables in the form 'key1=value1 key2=value2'
runs:
  using: 'docker'
  image: 'docker://beastawakens/action-convox-multi-slim:v1.0.23'