name: Convox Multitool
description: Convox CLI interface
author: Beast Awakens
icon: cloud
color: blue
inputs:
  action:
    description: Convox command to action
    required: true
    type: choice
    options:
      - build
      - build-migrate
      - create
      - deploy
      - destroy
      - login
      - promote
      - run
  password:
    description: Convox deploy key value
  host:
    description: Convox Console host address
    required: false
    default: console.convox.com
  rack:
    description: Convox Rack name
  app:
    description: Convox app name
  destination-app:
    description: Convox destination app name for build migration
  destination-rack:
    description: Convox destination rack name for build migration
  description:
    description: Convox build description
  cached:
    description: Whether to utilise the docker cache during the build
    required: false
    default: true
  manifest:
    description: Use a custom path for your convox.yml
    required: false
  release:
    description: ID of the release to promote. Only needed if you have not run a build step first or you wish to override the release id from the build
    required: false
  service:
    description: The service to run the command against
  command:
    description: The command to be run
outputs:
  release:
    description: Release ID of the created build
runs:
  using: 'docker'
  image: 'docker://beastawakens/action-convox-multi-slim:v1.0.5